language: rust
sudo: false
rust:
  - 1.16.0
  - stable
  - beta
  - nightly
install:
  - '[ "$TRAVIS_RUST_VERSION" == "1.16.0" ] || rustup target add thumbv6m-none-eabi'
script:
  - cargo build --verbose
  - cargo build --verbose --features serde
  - cargo build --verbose --features std
  - '[ "$TRAVIS_RUST_VERSION" == "1.16.0" ] || cargo build --verbose --target=thumbv6m-none-eabi'
  - cargo test --verbose
  - cargo test --verbose --features serde
  - cargo test --verbose --features std
  - cargo run --verbose --manifest-path test_max_level_features/Cargo.toml
  - cargo run --verbose --manifest-path test_max_level_features/Cargo.toml --release

notifications:
  email:
    on_success: never
